### ISSUE TITLE
Channels are still connected although not visible

### ISSUE THREAD

**Issue by simongregorebner** [caqtdm/caqtdm#33]
It is reported that all channels of a (complex) panel are always connected although they are not visible (e.g. are on a tab that is not visible). Pleople claim that ideally channels are disconnected in that case...

**Comment by AntonMezger** [comment]
Sorry,

this is not an issue!!! there are many reasons that channels are connected at startup. for invisible channels (not all depending on  the graphical object) the data flow is stopped in order to have less data transfers on the network.

people claiming that channels are not disconnected should propably organize their data screens in another way instead of having screens with over 3000 channels, started by over 10 instances. there is no way that with epics connecting directly to the ioc's this can be improved.

**Comment by simongregorebner** [comment]
This behaviour can now be controlled with this environment variable:

```CAQTDM_OPTIMIZE_EPICS3CONNECTIONS=TRUE```
