### ISSUE TITLE
Incorrect caLabel Rich Text Size

### ISSUE THREAD

**Issue by keenanlang** [caqtdm/caqtdm#34]
caLabels using rich text seem to do size calculations based off of the entire markup generated rather than the display size of the text. This not only causes font scaling to mess up, but also ruins layouts.

### Font Scaling

- Make a caLabel
- Change FontScaleMode to "WidthAndHeight"
- Open the 'edit text' display
- Give the label the text "TEST" and make it bold in the Rich Text area

**Expected Result**: The label will scale the font in order to fit "TEST" nicely within the width and height of the widget, and then uses that font to display the text, "TEST" in bold.

**Actual Result**: The label instead scales the font in order to fit 
`<html><head/><body><p><span style=" font-weight:600;">TEST</span></p></body></html> `
within the width and height of the widget, and then uses that font to display the text, "TEST" in bold.

### Layout Problems

- Take the previous caLabel we created and put it in a frame
- Add another widget to the frame
- Set both the label's and the widget's horizontal size policy to expanding
- Set the frame to a horizontal layout
- Set the layout's horizontal stretch factor to 1,1

**Expected Result**: The label and the widget will equally cover the frame's horizontal width

**Actual Result**: The label has been given a hidden minimum width according to the size of 
`<html><head/><body><p><span style=" font-weight:600;">TEST</span></p></body></html>`
 which causes the label to take up most of the frame.

**Comment by AntonMezger** [comment]
Actually we did not do anything in order to take into account rich text.

I will look into it next week

Envoyé de mon iPhone

Le 16 févr. 2018 à 22:30, Keenan Lang <notifications@github.com<mailto:notifications@github.com>> a écrit :


caLabels using rich text seem to do size calculations based off of the entire markup generated rather than the display size of the text. This not only causes font scaling to mess up, but also ruins layouts.

Steps to Replicate:
Font Scaling

  *   Make a caLabel
  *   Change FontScaleMode to "WidthAndHeight"
  *   Open the 'edit text' display
  *   Give the label the text "TEST" and make it bold

Expected Result: The label will scale the font in order to fit "TEST" nicely within the width and height of the widget, and then uses that font to display the text, "TEST" in bold.

Actual Result: The label instead scales the font in order to fit "

TEST

" within the width and height of the widget, and then uses that font to display the text, "TEST" in bold.

Layout Problems

  *   Take the previous caLabel we created and put it in a frame
  *   Add another widget to the frame
  *   Set both the label's and the widget's horizontal size policy to expanding
  *   Set the frame to a horizontal layout
  *   Set the layout's horizontal stretch factor to 1,1

Expected Result: The label and the widget will equally cover the frame's horizontal width

Actual Result: The label has been given a hidden minimum width according to the size of "

TEST

" which causes the label to take up most of the frame.

**Comment by AntonMezger** [comment]
fontscaling will take richtext into account. new version will be available on 21.2.18

**Comment by keenanlang** [comment]
Rich Text fontscaling still has issues while in a grid layout. The label seems to be set with a minimum width equivalent to the full generated html. I can work around this by setting the label's minimum width to 1, which causes it to scale correctly, but is strange considering that using just plain text doesn't seem to set any minimum width at all.
