### ISSUE TITLE
caCamera widget crashes application

### ISSUE THREAD

**Issue by prjemian** [caqtdm/caqtdm#38]
Using AreaDetector's ADSimDetector with Sensor size 1024x1024 and Binning 31x53 so final Image Size of CAM1 is 33x19.

Using caQtDM from master branch today (hash 1f91cd9d, v4.2.1_Development) built with EPICS Base 3.15.5 and Qt 4

When only the ADBase.ui screen is open (and no screen showing the caCamera widget), can set Image mode to Multiple or Continuous and acquire images without problems.

The problem is triggered when the ad_cam_image.ui screen (areaDetector/ADCore/ADApp/op/ui/ad_cam_image.ui) is displayed, the caQtDM application quits after a few images are collected.  The application crash depends on the "Auto:" checkbox selection.  Unselected, no problem.  Selected, crash in a few images.

This is the instance of `caCamera` in ad_cam_image.ui:
```
   <widget class="caCamera" name="Cam29id_ps6">
    <property name="geometry">
     <rect>
      <x>10</x>
      <y>60</y>
      <width>481</width>
      <height>251</height>
     </rect>
    </property>
    <property name="sizePolicy">
     <sizepolicy hsizetype="MinimumExpanding" vsizetype="MinimumExpanding">
      <horstretch>0</horstretch>
      <verstretch>0</verstretch>
     </sizepolicy>
    </property>
    <property name="channelData" stdset="0">
     <string notr="true">$(P)image1:ArrayData</string>
    </property>
    <property name="channelWidth" stdset="0">
     <string notr="true">$(P)image1:ArraySize0_RBV</string>
    </property>
    <property name="channelHeight" stdset="0">
     <string notr="true">$(P)image1:ArraySize1_RBV</string>
    </property>
    <property name="channelCode" stdset="0">
     <string notr="true">$(P)image1:DataType_RBV</string>
    </property>
    <property name="channelBPP" stdset="0">
     <string notr="true">$(P)image1:DataType_RBV</string>
    </property>
    <property name="Zoom" stdset="0">
     <enum>caCamera::Yes</enum>
    </property>
    <property name="automaticLevels" stdset="0">
     <bool>false</bool>
    </property>
    <property name="ColorMap" stdset="0">
     <enum>caCamera::grey</enum>
    </property>
   </widget>
```
In this case with the ADSimDetector, `P=13SIM1:`

Note, this same pattern did not crash the application with build v4.1.6_Development_e576f5c8.  I have tested this behavior with the same ADSimDetector build using the two different caQtDM versions and can reproduce the application crash.

The use of Image Binning may also be a factor in addition to the autoscale selection.

The next table shows the outcome for each combination tested with the goal of acquiring 100 images in Multiple mode.

version | Auto | Binning | outcome
------- | -------- | -------- | --------
v4.1.6_Development_e576f5c8 | checked | 31x53 | no crash
V4.1.8 (4df2916) | unchecked | 31x53 | no crash
V4.1.8 (4df2916) | checked | 31x53 | no crash
V4.2.0 (184fc6d) | unchecked | 31x53 | no crash
V4.2.0 (184fc6d) | checked | 31x53 | crash
V4.2.0 (184fc6d) | unchecked | -1x-1 (full image) | no crash
V4.2.0 (184fc6d) | checked | -1x-1 (full image) | no crash
v4.2.1_Development_1f91cd9d | unchecked | 31x53 | no crash
v4.2.1_Development_1f91cd9d | checked | 31x53 | crash

**Comment by AntonMezger** [comment]
I will take a look in about 10 days, while I am mext week not at PSI

Regards

Anton

Envoyé de mon iPhone

Le 17 mars 2018 à 12:21, Pete R Jemian <notifications@github.com<mailto:notifications@github.com>> a écrit :


Using AreaDetector's ADSimDetector with Sensor size 1024x1024 and Binning 31x53 so final Image Size of CAM1 is 33x19.

Using caQtDM from master branch today (hash 1f91cd9<https://github.com/caqtdm/caqtdm/commit/1f91cd9d141e01204498db86ab6eddf524ef2218>, v4.2.1_Development) built with EPICS Base 3.15.5 and Qt 4

When only the ADBase.ui screen is open (and no screen showing the caCamera widget), can set Image mode to Multiple or Continuous and acquire images without problems.

This is the instance of caCamera in that .ui file:

   <widget class="caCamera" name="Cam29id_ps6">
    <property name="geometry">
     <rect>
      <x>10</x>
      <y>60</y>
      <width>481</width>
      <height>251</height>
     </rect>
    </property>
    <property name="sizePolicy">
     <sizepolicy hsizetype="MinimumExpanding" vsizetype="MinimumExpanding">
      <horstretch>0</horstretch>
      <verstretch>0</verstretch>
     </sizepolicy>
    </property>
    <property name="channelData" stdset="0">
     <string notr="true">$(P)image1:ArrayData</string>
    </property>
    <property name="channelWidth" stdset="0">
     <string notr="true">$(P)image1:ArraySize0_RBV</string>
    </property>
    <property name="channelHeight" stdset="0">
     <string notr="true">$(P)image1:ArraySize1_RBV</string>
    </property>
    <property name="channelCode" stdset="0">
     <string notr="true">$(P)image1:DataType_RBV</string>
    </property>
    <property name="channelBPP" stdset="0">
     <string notr="true">$(P)image1:DataType_RBV</string>
    </property>
    <property name="Zoom" stdset="0">
     <enum>caCamera::Yes</enum>
    </property>
    <property name="automaticLevels" stdset="0">
     <bool>false</bool>
    </property>
    <property name="ColorMap" stdset="0">
     <enum>caCamera::grey</enum>
    </property>
   </widget>


In this case with the ADSimDetector, P=13SIM1:

The problem is triggered when the ad_cam_image.ui screen (areaDetector/ADCore/ADApp/op/ui/ad_cam_image.ui) is displayed, the caQtDM application quits after a few images are collected. The application crash depends on the "Auto:" checkbox selection. Unselected, no problem. Selected, crash in a few images.

Note, this same pattern did not crash the application with build v4.1.6_Development_e576f5c8. I have tested this behavior with the same ADSimDetector build using the two different caQtDM versions and can reproduce the application crash.

The use of Image Binning may also be a factor in addition to the autoscale selection.

The next table shows the outcome for each combination tested with the goal of acquiring 100 images in Multiple mode.

version Auto    Binning outcome
v4.1.6_Development_e576f5c8     checked 31x53   no crash
V4.1.8 (4df2916<https://github.com/caqtdm/caqtdm/commit/4df291606672ea28408abe2068a6d869276ea159>)      unchecked       31x53   no crash
V4.1.8 (4df2916<https://github.com/caqtdm/caqtdm/commit/4df291606672ea28408abe2068a6d869276ea159>)      checked 31x53   no crash
V4.2.0 (184fc6d<https://github.com/caqtdm/caqtdm/commit/184fc6ddf6f12dbaa9417400b4181d0108b3c127>)      unchecked       31x53   no crash
V4.2.0 (184fc6d<https://github.com/caqtdm/caqtdm/commit/184fc6ddf6f12dbaa9417400b4181d0108b3c127>)      checked 31x53   crash
V4.2.0 (184fc6d<https://github.com/caqtdm/caqtdm/commit/184fc6ddf6f12dbaa9417400b4181d0108b3c127>)      unchecked       -1x-1 (full image)      no crash
V4.2.0 (184fc6d<https://github.com/caqtdm/caqtdm/commit/184fc6ddf6f12dbaa9417400b4181d0108b3c127>)      checked -1x-1 (full image)      no crash
v4.2.1_Development_1f91cd9d     unchecked       31x53   no crash
v4.2.1_Development_1f91cd9d     checked 31x53   crash

From this table, it seems that caCamera's autoscale feature is crashing for binned images.

**Comment by HelgeBrands** [comment]
I found a problem with the X-server under Linux. On Windows the problem is not reproducible.

**Comment by HelgeBrands** [comment]
found a small problem can you check if it is the solution for you?

**Comment by prjemian** [comment]
tested from the Development branch and that works (with auto checked and 31x53 binning, able to collect thousands of continuous images with no crash)

**Comment by prjemian** [comment]
Your commit 65549ee5920b resolved the problem for me.  Thanks!
