### ISSUE TITLE
-attach stops working

### ISSUE THREAD

**Issue by timmmooney** [caqtdm/caqtdm#39]
A user reports that after caQtDM has been running for some time, the "-attach" argument no longer works, and a new instance of caQtDM is started with each new commandline invocation of "caQtDM -attach <filename>" 

If the workstation is rebooted, then caQtDM again honors the "-attach" argument, but again, after some time, stops honoring it.

This happens with more than one version of caQtDM, but I haven't done a systematic study.  I tracked this to something called sharedMemory, but I don't know how to take it further.

**Comment by AntonMezger** [comment]
Hi,

What plattform you are using? We did not notice this problem, so I would have to study this under your conditions.

Best regards

Anton

Envoyé de mon iPhone

Le 20 mars 2018 à 13:13, Tim Mooney <notifications@github.com<mailto:notifications@github.com>> a écrit :


A user reports that after caQtDM has been running for some time, the "-attach" argument no longer works, and a new instance of caQtDM is started with each new commandline invocation of "caQtDM -attach "

If the workstation is rebooted, then caQtDM again honors the "-attach" argument, but again, after some time, stops honoring it.

This happens with more than one version of caQtDM, but I haven't done a systematic study. I tracked this to something called sharedMemory, but I don't know how to take it further.

**Comment by timmmooney** [comment]
The guy who reported the problem is using "CentOS-7.4 (or whatever is the latest) with Mate Desktop."  He doesn't have a system in this state right now.  If he does get a system in the error state, he's offered to preserve it in that state until someone can examine it.  He says he can provide "TeamViewer access" (I haven't looked into how to do that).  Do you have a suggestion about how to get useful diagnostic information?

**Comment by AntonMezger** [comment]
Next week I will be able to take a look at it when it happens. However I will need some time to find out what to look at.

Regards

Envoyé de mon iPhone

Le 21 mars 2018 à 12:56, Tim Mooney <notifications@github.com<mailto:notifications@github.com>> a écrit :


The guy who reported the problem is using "CentOS-7.4 (or whatever is the latest) with Mate Desktop." He doesn't have a system in this state right now. If he does get a system in the error state, he's offered to preserve it in that state until someone can examine it. He says he can provide "TeamViewer access" (I haven't looked into how to do that). Do you have a suggestion about how to get useful diagnostic information?

**Comment by AntonMezger** [comment]
Problem solved (getuid in key)
